name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: checkout
        uses: actions/checkout@v3
        continue-on-error: true

      - id: hado
        name: hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yml
        continue-on-error: true

      - id: buildpush
        uses: docker/build-push-action@v3
        name: Build and push image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile
          repository: edgd1er/webnut
          tags: latest
