name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: checkout
        uses: actions/checkout@v2
        continue-on-error: true
        run: ls -alR

      - id: hado
        name: hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - id: buildpush
        uses: docker/build-push-action@v2.5.0
        name: Build and push image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile
          repository: edgd1er/webnut
          tags: latest
